# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  # If true, increase the height of the focused side window; creating an accordion
  # effect.
  expandFocusedSidePanel: true
  # The weight of the expanded side panel, relative to the other panels. 2 means
  # twice as tall as the other panels. Only relevant if `expandFocusedSidePanel`
  # is true.
  expandedSidePanelWeight: 4
  # If true, show the number of lines changed per file in the Files view
  showNumstatInFilesView: true
  # Nerd fonts version to use.
  # One of: '2' | '3' | empty string (default)
  # If empty, do not show icons.
  nerdFontsVersion: '3'
  # Whether to show the divergence from the base branch in the branches view.
  # One of: 'none' | 'onlyArrow'  | 'arrowAndNumber'
  showDivergenceFromBaseBranch: arrowAndNumber
  # Whether to split the main window when viewing file changes.
  # One of: 'auto' | 'always'
  # If 'auto', only split the main window when a file has both staged and unstaged
  # changes
  splitDiff: auto
  # How things are filtered when typing '/'.
  # One of 'substring' (default) | 'fuzzy'
  filterMode: fuzzy
git:
  pagers:
    - pager: delta --color-only
